riscv64: Add support for riscv64
This patch add riscv64 build support:
1, ppl.hh and ppl_c.h are added riscv32/riscv64 support
2, increase release number.

If we did not fix (1), when we built another package which depends on
ppl (like polymake), will meet this issue:
bundled extension ppl ... failed
ERROR:
The bundled extension ppl was explicitly requested but failed to configure.
Please recheck your argument (--with-ppl=/usr) and build.riscv64/bundled.log .
You can also disable it by specifying --without-ppl instead.
error: Bad exit status from /var/tmp/rpm-tmp.* (%build)

Reviewed-by: Wei Fu <wefu@redhat.com>
Signed-off-by: Zhengyu He <hezhy472013@gmail.com>